apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kellnr.fullname" . }}
  labels:
    {{- include "kellnr.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: {{ .Values.strategy.type }}
    {{- if eq .Values.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
    {{- end}}
  selector:
    matchLabels:
      {{- include "kellnr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- /* This annotation is used to trigger a rolling update when the config changes */}}
        {{- if .Values.secret.enabled }}
        secretHash: {{ include (print $.Template.BasePath "/secret-config.yaml") . | sha256sum }}
        {{- else }}
        configHash: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kellnr.selectorLabels" . | nindent 8 }}
    spec:
      {{- if or .Values.pvc.enabled .Values.importCert.enabled }}
      volumes:
        {{- if .Values.pvc.enabled }}
        - name: {{ .Values.deployment.volumes.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.deployment.volumes.persistentVolumeClaim }}
        {{- end }}
        {{- if .Values.importCert.enabled }}
        - name: {{ .Values.importCert.volumeName | quote }}
          configMap:
            name: {{ .Values.importCert.configMapName | quote }}
        {{- end }}
        - name: certs
          emptyDir: {}
        - name: tmp
          emptyDir: {}
      {{- end }}
      {{- if .Values.dns.enabled }}
      dnsPolicy: {{ .Values.dns.dnsPolicy | quote }}
      dnsConfig:
        nameservers:
          {{- toYaml .Values.dns.dnsConfig.nameservers | nindent 12 }}
        searches:
          {{- toYaml .Values.dns.dnsConfig.searches | nindent 12 }}
      {{- end }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kellnr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if eq .Values.kellnr.log.level "debug" }}
          - name: RUST_BACKTRACE
            value: "1"
          {{- end }}
          {{- if .Values.kellnr.postgres.enabled }}
          - name: KELLNR_POSTGRESQL__PWD
            valueFrom:
              secretKeyRef: {{ toYaml .Values.kellnr.postgres.pwdSecretRef | nindent 16 }}
          {{- end }}
          envFrom:
            {{- if .Values.secret.enabled }}
            - secretRef:
                name: {{ .Values.secret.name | quote }}
            {{- else }}
            - configMapRef:
                name: {{ .Values.configMap.name | quote }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.api.port }}
              name: kellnr-api
              protocol: TCP
          {{- if or .Values.pvc.enabled .Values.importCert.enabled }}
          volumeMounts:
            {{- if .Values.pvc.enabled }}
            - mountPath: {{ .Values.kellnr.registry.dataDir | quote }}
              name: {{ .Values.deployment.volumes.name }}
              readOnly: false
            {{- end }}
            {{- if .Values.importCert.enabled }}
            - name: {{ .Values.importCert.volumeName }}
              mountPath: "/usr/local/share/ca-certificates/"
              readOnly: true
            {{- end }}
            - mountPath: /etc/ssl/certs
              name: certs
            - mountPath: /tmp
              name: tmp
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
