{{- if .Values.httproute.enabled -}}
{{- $fullName := include "kellnr.fullname" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "kellnr.labels" . | nindent 4 }}
  {{- with .Values.httproute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.httproute.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.httproute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- else }}
  hostnames:
    - {{ .Values.kellnr.origin.hostname | quote }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: {{ .Values.httproute.pathType }}
            value: {{ .Values.httproute.path }}
      backendRefs:
        - name: {{ $fullName }}
          port: {{ .Values.service.api.port }}
      {{- with .Values.httproute.filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
