{{- if and .Values.secret.enabled (not .Values.secret.useExisting) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | quote }}
type: Opaque
stringData:
  KELLNR_SETUP__ADMIN_PWD: {{ .Values.kellnr.setup.adminPwd | toString | quote }}
  KELLNR_SETUP__ADMIN_TOKEN: {{ .Values.kellnr.setup.adminToken | toString | quote }}
  KELLNR_REGISTRY__DATA_DIR: {{ .Values.kellnr.registry.dataDir | toString | quote }}
  KELLNR_REGISTRY__SESSION_AGE_SECONDS: {{ .Values.kellnr.registry.sessionAgeSeconds | toString | quote }}
  KELLNR_REGISTRY__CACHE_SIZE: {{ .Values.kellnr.registry.cacheSize | toString | quote }}
  KELLNR_REGISTRY__MAX_CRATE_SIZE: {{ .Values.kellnr.registry.maxCrateSize | toString | quote }}
  KELLNR_REGISTRY__AUTH_REQUIRED: {{ .Values.kellnr.registry.authRequired | toString | quote }}
  KELLNR_DOCS__ENABLED: {{ .Values.kellnr.docs.enabled | toString | quote }}
  KELLNR_DOCS__MAX_SIZE: {{ .Values.kellnr.docs.maxSize | toString | quote }}
  KELLNR_PROXY__ENABLED: {{ .Values.kellnr.proxy.enabled | toString | quote }}
  KELLNR_PROXY__NUM_THREADS: {{ .Values.kellnr.proxy.numThreads | toString | quote }}
  KELLNR_PROXY__DOWNLOAD_ON_UPDATE: {{ .Values.kellnr.proxy.downloadOnUpdate | toString | quote }}
  KELLNR_LOG__LEVEL: {{ .Values.kellnr.log.level | toString | quote }}
  KELLNR_LOG__FORMAT: {{ .Values.kellnr.log.format | toString | quote }}
  KELLNR_LOG__LEVEL_WEB_SERVER: {{ .Values.kellnr.log.levelWebServer | toString | quote }}
  KELLNR_LOCAL__IP: {{ .Values.kellnr.local.ip | toString | quote }}
  KELLNR_LOCAL__PORT: {{ .Values.service.api.port | toString | quote }}
  KELLNR_ORIGIN__HOSTNAME: {{ required "A valid hostname, where Kellnr will be reachable is required." .Values.kellnr.origin.hostname | toString | quote }}
  KELLNR_ORIGIN__PORT: {{ include "kellnr.serviceOriginPort" . | quote }}
  KELLNR_ORIGIN__PROTOCOL: {{ .Values.kellnr.origin.protocol | toString | quote }}
  KELLNR_POSTGRESQL__ENABLED: {{ .Values.kellnr.postgres.enabled | toString | quote }}
  KELLNR_POSTGRESQL__ADDRESS: {{ .Values.kellnr.postgres.address | toString | quote }}
  KELLNR_POSTGRESQL__PORT: {{ .Values.kellnr.postgres.port | toString | quote }}
  KELLNR_POSTGRESQL__USER: {{ .Values.kellnr.postgres.user | toString | quote }}
  KELLNR_POSTGRESQL__DB: {{ .Values.kellnr.postgres.db | toString | quote }}
  KELLNR_S3__ENABLED: {{ .Values.kellnr.s3.enabled | toString | quote }}
  KELLNR_S3__ACCESS_KEY: {{ .Values.kellnr.s3.accessKey | toString | quote }}
  KELLNR_S3__SECRET_KEY: {{ .Values.kellnr.s3.secretKey | toString | quote }}
  KELLNR_S3__REGION: {{ .Values.kellnr.s3.region | toString | quote }}
  KELLNR_S3__ENDPOINT: {{ .Values.kellnr.s3.endpoint | toString | quote }}
  KELLNR_S3__ALLOW_HTTP: {{ .Values.kellnr.s3.allowHttp | toString | quote }}
  KELLNR_S3__CRATES_BUCKET: {{ .Values.kellnr.s3.crates_bucket | toString | quote }}
  KELLNR_S3__CRATESIO_BUCKET: {{ .Values.kellnr.s3.cratesio_bucket | toString | quote }}
{{- end }}
